blank_issues_enabled: false
contact_links:
  - name: ðŸ’¬ Questions or Discussion
    url: https://github.com/AndriiSynytsia/subscription-tracker/discussions
    about: Please use GitHub Discussions for general questions.
